[build]
  # Directorio de publicación (donde están los archivos web)
  publish = "public"
  
  # Comando de construcción (ejecuta el análisis antes del despliegue)
  command = "python src/nasdaq_analyzer.py"

[build.environment]
  # Versión de Python
  PYTHON_VERSION = "3.9"

# Configuración de redirecciones
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para archivos JSON
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

# Configuración para archivos estáticos
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración de funciones (para análisis automático)
[functions]
  directory = "netlify/functions"

# Variables de entorno (configurar en Netlify UI)
# NASDAQ_API_KEY = "tu_api_key_aqui"
# TIMEZONE = "Europe/Madrid"