[build]
  # Directorio de publicación (donde están los archivos web)
  publish = "public"
  
  # Comando de construcción (instala dependencias, ejecuta el análisis y copia datos)
  command = "npm install && pip install -r requirements.txt && python src/nasdaq_analyzer.py && mkdir -p public/data && cp -r data/* public/data/ 2>/dev/null || true"

[build.environment]
  # Versión de Python
  PYTHON_VERSION = "3.9"
  # Versión de Node.js (para funcionalidades futuras)
  NODE_VERSION = "18"

# Configuración de funciones serverless
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["child_process", "fs", "path"]
  included_files = ["scripts/**", "src/**", "requirements.txt"]

# Configuración de redirecciones
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/data/*"
  to = "/data/:splat"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuración para archivos JSON
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

# Configuración para archivos estáticos
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Variables de entorno (configurar en Netlify UI)
# NASDAQ_API_KEY = "tu_api_key_aqui"
# TIMEZONE = "Europe/Madrid"